[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  functions = "netlify/functions"

# Environment variables for production
[context.production.environment]
  VITE_DEV_MODE = "false"

[context.deploy-preview.environment]
  VITE_DEV_MODE = "true"